@startuml
class MouseController {
    humanPlayer : HumanPlayer
    cardController : CardController
    <<new>> camera : Camera
    <<new>> collider2D : Collider2D
    canBePlayed : bool
}
MonoBehaviour <|-- MouseController
@enduml
